### ISSUE TITLE
Incomplete python instructions

### ISSUE THREAD

**Issue by locks** [fzerocentral/fzgx-image2emblem#4]
I tried to run the python converter but got this error:

```
$ python image2emblem.py emblem.png
Traceback (most recent call last):
  File "image2emblem.py", line 10, in <module>
    from emblem import emblem_maker
  File "/Users/ricardo/src/_fzc/fzgx-image2emblem/python/emblem.py", line 12, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by JoselleAstrid** [comment]
Have you installed the Pillow package? You can run `pip list` to check if it's installed. If it's not, run `pip install Pillow` and try again.
